apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    k8s-app: grafana-operator
    operator: grafana
  name: grafana-operator
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        k8s-app: grafana-operator
        operator: grafana
    spec:
      containers:
      - name: grafana-operator
        image: {{ .Values.grafana.watcher.image }}
        imagePullPolicy: IfNotPresent
        args:
        - "-grafana-url={{ .Values.grafana.url }}"
        ports:
        - containerPort: {{ .Values.grafana.watcher.containerPort }}
          name: http
          protocol: TCP
        env:
        - name: GRAFANA_USER
          valueFrom:
            secretKeyRef:
              name: grafana-auth
              key: username
        - name: GRAFANA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: grafana-auth
              key: password
        resources:
{{ toYaml .Values.grafana.watcher.resources | indent 11 }}  
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      {{- if .Values.grafana.watcher.serviceAccount }}
      serviceAccountName: {{ .Values.grafana.watcher.serviceAccount }}
      {{- end }}