apiVersion: v1
kind: Secret
metadata:
  name: grafana-auth
  labels:
    app: {{ .Values.name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
type: Opaque
data:
  username:  {{ b64enc .Values.grafana.auth.username }}
  password: {{ b64enc .Values.grafana.auth.password }}
